### ISSUE TITLE
Security Risk on Random Generator

### ISSUE THREAD

**Issue by vang1ong7ang** [the-tunnel/tt#1]
The following random generator may have security risks.

```rust
pub fn get_random_bytes() -> Vec<u8> {
    let mut rng = rand::thread_rng();
    let mut length = rng.gen_range(12, 33);
    let mut result = Vec::with_capacity(length);
    while length > 0  {
        result.push(rng.gen::<u8>());
        length -= 1;
    };
    result
}
```

As it mentioned in <https://rust-num.github.io/num/rand/index.html>

> An application that requires an entropy source for cryptographic purposes must use `OsRng`, which reads randomness from the source that the operating system provides (e.g. `/dev/urandom` on Unixes or `CryptGenRandom()` on Windows). The other random number generators provided by this module are not suitable for such purposes.

**Comment by elderking** [comment]
Actually, the lastest doc of [rand](https://rust-random.github.io/rand/rand/rngs/index.html) says:
> ThreadRng, provided by the thread_rng function, is a handle to a thread-local CSPRNG with periodic seeding from OsRng. Because this is local, it is typically much faster than OsRng. It should be secure, though the paranoid may prefer OsRng.

So, we will stick to ```thread_rng``` here.
thanks anyway.
